package com.example.travelhut.model.utils;

public class StringsRepository {

    public final static String USERS_CAP = "Users";
    public final static String USER_CREATED = "User Created";
    public final static String REG_FAILED = "Registration Failed";
    public final static String ID = "id";
    public final static String USERNAME = "username";
    public final static String EMAIL = "email";
    public final static String IMAGE_URL = "imageurl";
    public final static String PLACEHOLDER_PROFILE_IMAGE_URL = "https://firebasestorage.googleapis.com/v0/b/travelhut-a660a.appspot.com/o/placeholder.png?alt=media&token=cf4b797a-3daf-43d6-b9a4-83383347bb0e";
    public final static String LOGIN_FAILED = "Login Failed";
    public final static String FOLLOW_CAP = "Follow";
    public final static String FOLLOW = "follow";
    public final static String FOLLOWERS = "followers";
    public final static String ON_ACTIVE = "onActive";
    public final static String ON_INACTIVE = "onInactive";
    public final static String FOLLOWING = "following";
    public final static String POSTS_CAP = "Posts";
    public final static String POSTS = "posts";
    public final static String POSTING_CAP = "Posting";
    public final static String POST_ID = "postid";
    public final static String POST_IMAGE = "postimage";
    public final static String DESCRIPTION = "description";
    public final static String PUBLISHER = "publisher";
    public final static String FAILED_CAP = "Failed";
    public final static String NO_IMAGE_SELECTED = "No Image Selected";
    public final static String SOMETHING_GONE_WRONG = "Something Gone Wrong";
    public final static String STORY_CAP = "Story";
    public final static String STORY = "story";
    public final static String STORY_START_TIME = "timestart";
    public final static String STORY_END_TIME = "timeend";
    public final static String STORY_ID = "storyid";
    public final static String USER_ID = "userid";
    public final static String FULL_STOP = ".";
    public final static String DISPLAY_NAME = "displayname";
    public final static String BIO = "bio";
    public final static String URL = "url";
    public final static String TEXT = "text";
    public final static String IS_POST = "ispost";
    public final static String NOTIFICATIONS_CAP = "Notifications";
    public final static String STARTED_FOLLOWING_YOU = "started following you";
    public final static String UPLOADS = "uploads";
    public final static String COMMENTS_CAP = "Comments";
    public final static String COMMENT = "comment";
    public final static String COMMENTED = "commented: ";
    public final static String TRIPS_CAP = "Trips";
    public final static String TRIPS = "trips";
    public final static String X_ACCESS_TOKEN = "X-Access-Token";
    public final static String TRAVEL_ADVICE_BASE_URL = "https://api.traveladviceapi.com/search/";
    public final static String TRAVEL_ADVICE_STATS_URL = "https://api.traveladviceapi.com/search/stats/";
    public final static String TRAVEL_ADVICE_STATS_URL_LIMITER_7 = "?limit=7";
    public final static String RECOMMENDATION = "recommendation";
    public final static String ADVICE = "advice";
    public final static String LEVEL_DESC = "level_desc";
    public final static String REQUIREMENTS = "requirements";
    public final static String MASKS = "masks";
    public final static String QAURANTINE = "quarantine";
    public final static String TESTS = "tests";
    public final static String APC_AUTH = "APC-Auth";
    public final static String APC_AUTH_SECRET = "APC-Auth-Secret";
    public final static String APC_AUTH_SECRET_VALUE = "851a3436d09953f";
    public final static String APC_AUTH_VALUE = "58953a2bf3";
    public final static String CONTENT_TYPE = "Content-Type";
    public final static String APPLICATION_JSON = "application/json";
    public final static String AIRPORT_CODES_URL = "https://www.air-port-codes.com/api/v1/multi?term=";
    public final static String AIRPORTS = "airports";
    public final static String IATA = "iata";
    public final static String DATE = "date";
    public final static String DATES = "dates";
    public final static String NEW_CASES = "new_cases";
    public final static String URL_CANT_BE_EMPTY = "URL can't be empty";
    public final static String EMPTY_STRING = "";
    public final static String USER_AGENT = "User-Agent";
    public final static String ANDROID = "android";
    public final static String ACCEPT_CAP = "Accept";
    public final static String TICKETMASTER_API_BASE_URL = "http://app.ticketmaster.com/discovery/v2/events.json?apikey=";
    public final static String _EMBEDDED = "_embedded";
    public final static String EVENTS = "events";
    public final static String NAME = "name";
    public final static String START = "start";
    public final static String LOCAL_DATE = "localDate";
    public final static String VENUES = "venues";
    public final static String IMAGES = "images";
    public final static String PREFS = "PREFS";
    public final static String PROFILE_ID = "profileid";
    public final static String PLACE_ID = "placeid";
    public final static String TRIP_ID = "tripid";
    public final static String EVENT_ID = "eventid";
    public final static String DATE_PICKER = "DATE_PICKER";
    public final static String PLACENAME = "placename";
    public final static String PLACEADDRESS = "placeaddress";
    public final static String DATERANGE = "daterange";
    public final static String STARTDATE = "startdate";
    public final static String ENDDATE = "enddate";
    public final static String PUBLISHERID = "publisherid";
    public final static String VIEWS = "views";
    public final static String WEATHER_API_URL_BASE = "https://api.openweathermap.org/data/2.5/onecall?lat=";
    public final static String WEATHER_API_URL_ICON = "http://openweathermap.org/img/wn/";
    public final static String TEMP = "temp";
    public final static String HUMIDITY = "humidity";
    public final static String ICON = "icon";
    public final static String CURRENT = "current";
    public final static String TIMEZONE_OFFSET = "timezone_offset";
    public final static String WEATHER = "weather";
    public final static String DT = "dt";
    public final static String SPACE_LIKES = " likes";
    public final static String LIKED_POST_NOTIFICATION_MESSAGE = "liked your post";


}
